### ISSUE TITLE
當打字很快的時候，會漏掉一些鍵

### ISSUE THREAD

**Issue by ilway25** [ethanliu/OkidoKeyCharsets#6]
使用 OkidoKey 打字很快的時候，如果 A 鍵按了，還沒放開，就按了 B 鍵，則 B 鍵會偵測不到。
必須確定 A 鍵放開了，這時才按 B 鍵，B 才會被偵測到。
這在打字很快的時候不好使用。

而且這和 iOS 14.7.1 的內建輸入法行為不一致，它在打字快的時候，不需等上一鍵放開，就可以偵測下一個鍵。

希望能增加這個選項。

**Comment by ethanliu** [comment]
app 的問題還請使用其他方式連繫，這邊比較單純只含有字根等資源的部份。

iOS 內建鍵盤與第三方輸入法，在實做完全完是兩種不同的模式，第三方輸入法只能盡可能的達到類似的功能。
OkidoKey 並未設計給多點接觸，一般模式下不支援滑動，所以這行為會變成避免誤觸按鍵，也就是忽略 B 鍵是正常的結果。

**Comment by ethanliu** [comment]
Closed due to lack of response
