### ISSUE TITLE
希望可以更新預測字詞中的emoji

### ISSUE THREAD

**Issue by q120144178** [ethanliu/OkidoKeyCharsets#7]
目前emoji已經更新好幾代了，但輸入法好像仍只支援早期的表情，新出的表情都無法輸入相當可惜！

**Comment by ethanliu** [comment]
其實一直有考慮要將 emoji 功能移除，在上個版本更新訊息中也有提到，未來版本將會移除 emoji 預測字詞。
其中一個原因便是更新上的問題，再讓我想想

**Comment by ethanliu** [comment]
原來之前一直沒發現 emoji cldr 也很完整，加上已有更方便使用 json 格式
省去了整理及翻譯的過程，所以 emoji 功能將會續存。

**Comment by q120144178** [comment]
那真是太好了！那未來的版本是否會更新新版的EMOJI呢

**Comment by ethanliu** [comment]
會支援現行版本，因為資料來源是 unicode.org 所以可以跟上更新的內容，目前是 v14

**Comment by ethanliu** [comment]
Emoji 已於付費版 v.2.6.0 免費版 v.2.6.1 更新。
